"""This module contains irregular nouns for function form_plural."""


nouns_not_changing = ['sheep', 'deer', 'bread', 'jeans', 'salmon', 'money', 'aircraft', 'crossroads']

irregular_nouns = [
    {'singular': 'man',
     'plural': 'men'},
    {'singular': 'woman',
     'plural': 'women'},
    {'singular': 'person',
     'plural': 'people'},
    {'singular': 'child',
     'plural': 'children'},
    {'singular': 'foot',
     'plural': 'feet'},
    {'singular': 'tooth',
     'plural': 'teeth'},
    {'singular': 'goose',
     'plural': 'geese'},
    {'singular': 'mouse',
     'plural': 'mice'},
    {'singular': 'ox',
     'plural': 'oxen'},
    {'singular': 'quiz',
     'plural': 'quizzes'},
    {'singular': 'photo',
     'plural': 'photos'},
    {'singular': 'piano',
     'plural': 'pianos'},
    {'singular': 'zero',
     'plural': 'zeros'},
]


other_nouns = [
    {'singular': 'automaton',
     'plural': 'automata'},
    {'singular': 'criterion',
     'plural': 'criteria'},
    {'singular': 'phenomenon',
     'plural': 'phenomena'},
    {'singular': 'ganglion',
     'plural': 'ganglia'},
    {'singular': 'perihelion',
     'plural': 'perihelia'},
    {'singular': 'vortex',
     'plural': 'vortices'},
    {'singular': 'appendix',
     'plural': 'appendices'},
    {'singular': 'helix',
     'plural': 'helices'},
    {'singular': 'matrix',
     'plural': 'matrices'},
    {'singular': 'index',
     'plural': 'indices'},
    {'singular': 'bacterium',
     'plural': 'bacteria'},
    {'singular': 'ovum',
     'plural': 'ova'},
    {'singular': 'millennium',
     'plural': 'millennia'},
    {'singular': 'stratum',
     'plural': 'strata'},
    {'singular': 'addendum',
     'plural': 'addenda'},
]
